/**
 * @file test_basic.cpp
 * @brief Basic tests for the cloud backend application.
 *
 * This file is generated by the Vix backend template. It provides a
 * minimal test executable to validate that the test runner is wired
 * correctly and that the generated project can compile test targets.
 */

#include <vix/tests/tests.hpp>

/**
 * @brief Run the generated backend test suite.
 *
 * The test executable owns its own main function and must not include
 * the application main.cpp file.
 *
 * @return Process exit code returned by the Vix test runner.
 */
int main()
{
  using namespace vix::tests;

  auto &registry = TestRegistry::instance();
  registry.clear();

  registry.add(TestCase("cloud backend basic test", []
  {
    Assert::equal(2 + 2, 4);
  }));

  registry.add(TestCase("cloud backend name is available", []
  {
    const char *name = "cloud";
    Assert::is_true(name != nullptr);
  }));

  return TestRunner::run_all_and_exit();
}
