#include <feedback/controllers/FeedbackController.hpp>
#include <auth/middleware/AuthMiddleware.hpp>
#include <feedback/services/FeedbackService.hpp>
#include <string>
#include <vix.hpp>
#include <vix/json.hpp>
namespace cloud::feedback::controllers { namespace { using cloud::auth::middleware::AuthContext; using cloud::feedback::services::FeedbackService; void err(vix::Response &res,int status,const std::string &c,const std::string &m){res.status(status).json(vix::json::o("ok",false,"error",c,"message",m));} AuthContext ctx(vix::Request &req){ try{return req.state<AuthContext>();}catch(...){return{};} } std::string s(vix::Request &req,const std::string &k){ if(req.body().empty()) return {}; try{const auto &b=req.json(); return b.is_object()?b.value(k,""):std::string{};}catch(...){return{};} } int i(vix::Request &req,const std::string &k,int d){ if(req.body().empty()) return d; try{const auto &b=req.json(); return b.is_object()&&b.contains(k)?b[k].get<int>():d;}catch(...){return d;} } void create(vix::Request &req,vix::Response &res){ auto c=ctx(req); dto::CreateFeedbackRequest q; q.user_id=c.user_id; q.workspace_id=s(req,"workspace_id"); q.category=s(req,"category"); q.title=s(req,"title"); q.message=s(req,"message"); FeedbackService service; auto r=service.create(q); if(r.failed()) return err(res,400,r.error_code(),r.error_message()); res.json(vix::json::o("ok",true,"data",r.value().to_json())); } void mine(vix::Request &req,vix::Response &res){ auto c=ctx(req); dto::ListFeedbackRequest q; q.user_id=c.user_id; q.limit=i(req,"limit",50); FeedbackService service; auto r=service.list_mine(q); if(r.failed()) return err(res,400,r.error_code(),r.error_message()); vix::json::Json items=vix::json::Json::array(); for(const auto &f:r.value()) items.push_back(f.to_json()); res.json(vix::json::o("ok",true,"data",vix::json::o("feedback",items))); } void workspace(vix::Request &req,vix::Response &res){ dto::ListFeedbackRequest q; q.workspace_id=s(req,"workspace_id"); q.limit=i(req,"limit",50); FeedbackService service; auto r=service.list_workspace(q); if(r.failed()) return err(res,400,r.error_code(),r.error_message()); vix::json::Json items=vix::json::Json::array(); for(const auto &f:r.value()) items.push_back(f.to_json()); res.json(vix::json::o("ok",true,"data",vix::json::o("feedback",items))); } void update(vix::Request &req,vix::Response &res){ auto c=ctx(req); dto::UpdateFeedbackStatusRequest q; q.feedback_id=s(req,"feedback_id"); q.workspace_id=s(req,"workspace_id"); q.actor_user_id=c.user_id; q.status=s(req,"status"); FeedbackService service; auto r=service.update_status(q); if(r.failed()) return err(res,400,r.error_code(),r.error_message()); res.json(vix::json::o("ok",true,"data",r.value().to_json())); } }
void FeedbackController::register_routes(vix::App &app){ app.post("/api/feedback/create", create); app.post("/api/feedback/list_mine", mine); app.post("/api/feedback/list_workspace", workspace); app.post("/api/feedback/update_status", update); }
}
