#include <notifications/services/NotificationService.hpp>
#include <notifications/support/NotificationRealtimeHub.hpp>
#include <atomic>
#include <chrono>
#include <cstdlib>
#include <memory>
#include <sstream>
#include <vix/config/Config.hpp>
#include <vix/db/db.hpp>

namespace cloud::notifications::services {
namespace {
std::int64_t now_ts(){ return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count(); }
std::string make_id(const char *p){ static std::atomic<std::uint64_t> c{0}; std::ostringstream s; s<<p<<"_"<<now_ts()<<"_"<<c.fetch_add(1); return s.str(); }
}
class NotificationService::Impl { public:
  Impl(){ const char *u=std::getenv("SOFTADASTRA_CLOUD_USE_DB"); if(u&&std::string(u)=="1"){ vix::config::Config cfg{".env"}; db=std::make_unique<vix::db::Database>(cfg);} }
  bool persistent() const { return db!=nullptr; }
  dto::NotificationResponse row(const vix::db::ResultRow &r) const { dto::NotificationResponse n; n.id=r.getString(0); n.workspace_id=r.getString(1); n.project_id=r.getString(2); n.recipient_user_id=r.getString(3); n.actor_user_id=r.getString(4); n.type=r.getString(5); n.title=r.getString(6); n.message=r.getString(7); n.data_json=r.getString(8); n.read_at=r.getInt64(9); n.created_at=r.getInt64(10); return n; }
  dto::PreferencesResponse pref_row(const vix::db::ResultRow &r) const { dto::PreferencesResponse p; p.id=r.getString(0); p.user_id=r.getString(1); p.workspace_id=r.getString(2); p.notify_invites=r.getInt64(3)!=0; p.notify_member_changes=r.getInt64(4)!=0; p.notify_tokens=r.getInt64(5)!=0; p.notify_projects=r.getInt64(6)!=0; p.notify_packages=r.getInt64(7)!=0; p.notify_lockfiles=r.getInt64(8)!=0; p.notify_build_reports=r.getInt64(9)!=0; p.notify_security=r.getInt64(10)!=0; p.created_at=r.getInt64(11); p.updated_at=r.getInt64(12); return p; }
  std::unique_ptr<vix::db::Database> db;
};
NotificationService::NotificationService(): impl_(std::make_unique<Impl>()){} NotificationService::~NotificationService()=default;
NotificationResult<dto::NotificationResponse> NotificationService::create(const dto::CreateNotificationRequest &q){ if(q.recipient_user_id.empty()) return NotificationResult<dto::NotificationResponse>::failure("missing_user","Recipient is required."); if(q.type.empty()) return NotificationResult<dto::NotificationResponse>::failure("invalid_notification","Notification type is required."); if(!impl_->persistent()) return NotificationResult<dto::NotificationResponse>::failure("notification_store_unavailable","Notification storage is unavailable."); dto::NotificationResponse n; n.id=make_id("notification"); n.workspace_id=q.workspace_id; n.project_id=q.project_id; n.recipient_user_id=q.recipient_user_id; n.actor_user_id=q.actor_user_id; n.type=q.type; n.title=q.title; n.message=q.message; n.data_json=q.data_json; n.created_at=now_ts(); impl_->db->exec("INSERT INTO notifications (id, workspace_id, project_id, recipient_user_id, actor_user_id, type, title, message, data_json, read_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)", n.id,n.workspace_id,n.project_id,n.recipient_user_id,n.actor_user_id,n.type,n.title,n.message,n.data_json,n.created_at); cloud::notifications::support::NotificationRealtimeEvent event; event.id=n.id; event.workspace_id=n.workspace_id; event.project_id=n.project_id; event.recipient_user_id=n.recipient_user_id; event.actor_user_id=n.actor_user_id; event.type=n.type; event.title=n.title; event.message=n.message; event.data_json=n.data_json; event.read_at=n.read_at; event.created_at=n.created_at; cloud::notifications::support::NotificationRealtimeHub::emit(event); return NotificationResult<dto::NotificationResponse>::success(n); }
NotificationResult<std::vector<dto::NotificationResponse>> NotificationService::list(const dto::ListNotificationsRequest &q) const { if(q.user_id.empty()) return NotificationResult<std::vector<dto::NotificationResponse>>::failure("missing_user","User is required."); std::vector<dto::NotificationResponse> out; if(!impl_->persistent()) return NotificationResult<std::vector<dto::NotificationResponse>>::success(out); const auto limit=q.limit>0&&q.limit<=200?q.limit:50; std::string filter=q.filter; if(filter=="unread"){ auto rows=impl_->db->query("SELECT id, COALESCE(workspace_id,''), COALESCE(project_id,''), recipient_user_id, COALESCE(actor_user_id,''), type, title, message, COALESCE(data_json,''), COALESCE(read_at,0), created_at FROM notifications WHERE recipient_user_id = ? AND read_at IS NULL ORDER BY created_at DESC LIMIT ?", q.user_id, static_cast<std::int64_t>(limit)); while(rows->next()) out.push_back(impl_->row(rows->row())); }
else if(filter=="read"){ auto rows=impl_->db->query("SELECT id, COALESCE(workspace_id,''), COALESCE(project_id,''), recipient_user_id, COALESCE(actor_user_id,''), type, title, message, COALESCE(data_json,''), COALESCE(read_at,0), created_at FROM notifications WHERE recipient_user_id = ? AND read_at IS NOT NULL ORDER BY created_at DESC LIMIT ?", q.user_id, static_cast<std::int64_t>(limit)); while(rows->next()) out.push_back(impl_->row(rows->row())); }
else if(!q.workspace_id.empty()){ auto rows=impl_->db->query("SELECT id, COALESCE(workspace_id,''), COALESCE(project_id,''), recipient_user_id, COALESCE(actor_user_id,''), type, title, message, COALESCE(data_json,''), COALESCE(read_at,0), created_at FROM notifications WHERE recipient_user_id = ? AND workspace_id = ? ORDER BY created_at DESC LIMIT ?", q.user_id,q.workspace_id, static_cast<std::int64_t>(limit)); while(rows->next()) out.push_back(impl_->row(rows->row())); }
else { auto rows=impl_->db->query("SELECT id, COALESCE(workspace_id,''), COALESCE(project_id,''), recipient_user_id, COALESCE(actor_user_id,''), type, title, message, COALESCE(data_json,''), COALESCE(read_at,0), created_at FROM notifications WHERE recipient_user_id = ? ORDER BY created_at DESC LIMIT ?", q.user_id, static_cast<std::int64_t>(limit)); while(rows->next()) out.push_back(impl_->row(rows->row())); } return NotificationResult<std::vector<dto::NotificationResponse>>::success(out); }
NotificationResult<int> NotificationService::unread_count(const std::string &u) const { if(u.empty()) return NotificationResult<int>::failure("missing_user","User is required."); auto rows=impl_->db->query("SELECT COUNT(*) FROM notifications WHERE recipient_user_id = ? AND read_at IS NULL", u); return NotificationResult<int>::success(rows->next()?static_cast<int>(rows->row().getInt64(0)):0); }
NotificationResult<dto::NotificationResponse> NotificationService::mark_read(const dto::NotificationActionRequest &q){ if(q.user_id.empty()||q.notification_id.empty()) return NotificationResult<dto::NotificationResponse>::failure("invalid_request","User and notification are required."); impl_->db->exec("UPDATE notifications SET read_at = COALESCE(read_at, ?) WHERE id = ? AND recipient_user_id = ?", now_ts(), q.notification_id, q.user_id); auto rows=impl_->db->query("SELECT id, COALESCE(workspace_id,''), COALESCE(project_id,''), recipient_user_id, COALESCE(actor_user_id,''), type, title, message, COALESCE(data_json,''), COALESCE(read_at,0), created_at FROM notifications WHERE id = ? AND recipient_user_id = ? LIMIT 1", q.notification_id,q.user_id); if(!rows->next()) return NotificationResult<dto::NotificationResponse>::failure("notification_not_found","Notification not found."); return NotificationResult<dto::NotificationResponse>::success(impl_->row(rows->row())); }
NotificationResult<int> NotificationService::mark_all_read(const std::string &u){ if(u.empty()) return NotificationResult<int>::failure("missing_user","User is required."); impl_->db->exec("UPDATE notifications SET read_at = COALESCE(read_at, ?) WHERE recipient_user_id = ? AND read_at IS NULL", now_ts(), u); return unread_count(u); }
NotificationResult<dto::PreferencesResponse> NotificationService::show_preferences(const dto::PreferencesRequest &q){ if(q.user_id.empty()) return NotificationResult<dto::PreferencesResponse>::failure("missing_user","User is required."); auto rows=impl_->db->query("SELECT id,user_id,COALESCE(workspace_id,''),notify_invites,notify_member_changes,notify_tokens,notify_projects,notify_packages,notify_lockfiles,notify_build_reports,notify_security,created_at,updated_at FROM notification_preferences WHERE user_id = ? AND COALESCE(workspace_id,'') = ? LIMIT 1", q.user_id,q.workspace_id); if(rows->next()) return NotificationResult<dto::PreferencesResponse>::success(impl_->pref_row(rows->row())); dto::PreferencesUpdateRequest u; u.user_id=q.user_id; u.workspace_id=q.workspace_id; return update_preferences(u); }
NotificationResult<dto::PreferencesResponse> NotificationService::update_preferences(const dto::PreferencesUpdateRequest &q){ if(q.user_id.empty()) return NotificationResult<dto::PreferencesResponse>::failure("missing_user","User is required."); auto id=make_id("notification_pref"); auto now=now_ts(); impl_->db->exec("INSERT INTO notification_preferences (id,user_id,workspace_id,notify_invites,notify_member_changes,notify_tokens,notify_projects,notify_packages,notify_lockfiles,notify_build_reports,notify_security,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id, workspace_id) DO UPDATE SET notify_invites=excluded.notify_invites, notify_member_changes=excluded.notify_member_changes, notify_tokens=excluded.notify_tokens, notify_projects=excluded.notify_projects, notify_packages=excluded.notify_packages, notify_lockfiles=excluded.notify_lockfiles, notify_build_reports=excluded.notify_build_reports, notify_security=excluded.notify_security, updated_at=excluded.updated_at", id,q.user_id,q.workspace_id,q.notify_invites,q.notify_member_changes,q.notify_tokens,q.notify_projects,q.notify_packages,q.notify_lockfiles,q.notify_build_reports,q.notify_security,now,now); return show_preferences({q.user_id,q.workspace_id}); }
NotificationResult<int> NotificationService::create_for_workspace_members(const dto::CreateNotificationRequest &q){ if(q.workspace_id.empty()) return NotificationResult<int>::failure("missing_workspace","Workspace is required."); int count=0; auto rows=impl_->db->query("SELECT owner_user_id FROM workspaces WHERE id = ? UNION SELECT user_id FROM workspace_members WHERE workspace_id = ? AND active = 1 AND status = 'active'", q.workspace_id,q.workspace_id); while(rows->next()){ auto c=q; c.recipient_user_id=rows->row().getString(0); if(c.recipient_user_id!=q.actor_user_id && create(c).ok()) ++count; } return NotificationResult<int>::success(count); }
NotificationResult<int> NotificationService::create_for_project_members(const dto::CreateNotificationRequest &q){ if(q.workspace_id.empty()||q.project_id.empty()) return NotificationResult<int>::failure("invalid_request","Workspace and project are required."); int count=0; auto rows=impl_->db->query("SELECT owner_user_id FROM workspaces WHERE id = ? UNION SELECT user_id FROM workspace_members WHERE workspace_id = ? AND active = 1 AND status = 'active' AND (COALESCE(access_scope,'entire_workspace') = 'entire_workspace' OR instr(COALESCE(project_ids_json,''), char(34) || ? || char(34)) > 0)", q.workspace_id,q.workspace_id,q.project_id); while(rows->next()){ auto c=q; c.recipient_user_id=rows->row().getString(0); if(c.recipient_user_id!=q.actor_user_id && create(c).ok()) ++count; } return NotificationResult<int>::success(count); }
}
